# Generated by roxytest: do not edit by hand!

# File R/do_nothing.R: @tests

c("## Function do.nothing() @ L28\nexpect_null(do.nothing())\nexpect_null(do.nothing(\"yowza!\"))\n", "## Function do.nothing() @ L28\nexpect_error({\n  setTimeLimit(elapsed=0.1)\n  do.nothing.else()\n},\npattern=\"reached elapsed time limit\"\n)\n")
