# Generated by roxytest: Do not edit by hand!

# File R/do_nothing.R: @tests

## Function do.nothing() @ L26
expect_null(do.nothing())
expect_null(do.nothing("yowza!"))


## Function do.nothing.else() @ L43
expect_error({
  setTimeLimit(elapsed=0.1,cpu=0.1)
  do.nothing.else()
},
pattern="reached elapsed time limit"
)

